name: Auto Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - run: ls ./
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Lmao
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew shadowJar
      - name: Set sha var
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - run: ls build/libs
      - name: Publish Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ steps.vars.outputs.sha_short }}
          prerelease: false
          title: 'Bot Release ${{ steps.vars.outputs.sha_short }}'
          files: build/libs/cs_dsbot-*.jar
