name: Auto Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Set SHA var
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 18

      - name: Lmao
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew shadowJar

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/cs_dsbot-*.jar
          name: Bot Release ${{steps.vars.outputs.sha_short}}
          tag_name: ${{steps.vars.outputs.sha_short}}
